- name: configure mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: Install MySQL server
    ansible.builtin.package:
      name: mysql-server
      state: installed

  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysql
      state: installed
      enabled: yes

  # - name: connect to mysql server


